name: mtg-ai-main
channels:
  - defaults
dependencies:
  - python=3.10.6
  - pip
  - pip:
    - base58==2.1.1
    - fpdf==1.7.2
    - matplotlib==3.6.2
    - nltk==3.7
    - pillow==9.3.0
    - pyyaml==5.4.1
    - requests==2.28.1
    - tabulate==0.9.0
    - titlecase==2.4
