name: torch-rnn
channels:
  - defaults
dependencies:
  - python=2.7.18
  - pip
  - lua=5.3.4
  - luarocks=3.7.0
  - pip:
    - Cython==0.23.4
    - numpy==1.10.4
    - argparse==1.2.1
    - h5py==2.5.0
    - six==1.10.0
  - luarocks:
    - torch
    - nn
    - optim
    - lua-cjson
    - cutorch
    - cunn
